name: Cleanup workflow runs

on:
  schedule:
    - cron: '0 16 * * 3'  # 每天凌晨运行
  workflow_dispatch: # 手动触发

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old workflow runs
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
